### ISSUE TITLE
Information about prerequisites in the readme

### ISSUE THREAD

**Issue by teltploek** [btford/angular-express-seed#7]
Hi,

First of all: Thanks for this! I was in the midst of building this sort of thing myself (because I needed it, and yeoman isn't offering express generators - which it probably is right about leaving out) but then I found this, saw your name on it and though; "well, this outta do it".

My issue:
Maybe it's me being new to expressJS and all this, but I thought this might help other newbies as well. The _"How to use angular-express-seed"_ only says _"Clone the angular-express-seed repository and start hacking!"_, but if you _only_ do this and run `node app.js` you'll end up missing express, jade (and maybe even other things)

You might say that people looking for a seed like this, already have these things installed if, but again; it could probably help newbies if the installation prerequisites were described as well. All in all it's a judgement call, but these were just my 5 cents.

Now, I'm off to hack at this - can't wait :-) ! Please let me know if you need help working on this in any way.

Best regards
Brian

**Comment by btford** [comment]
@teltploek glad you found it useful.

I added a note in 3f92e78f9c8129ece97227784c6c81e4cd59fd69 about npm install. Was there anything else you think should be added to make it easier for beginners?

Thanks for the offer. I can't think of anything urgent that needs doing, but feel free to file more issues and offer your suggestions!
