### ISSUE TITLE
Using this with socket.io

### ISSUE THREAD

**Issue by teltploek** [btford/angular-express-seed#8]
Hi,

I was trying to hook this up with socket.io, but I'm not sure how to do it.

As far I as can read from [Express - Migrating from 2.x to 3.x](https://github.com/visionmedia/express/wiki/Migrating-from-2.x-to-3.x) it instucts me to do it like this:

`var app = express()
  , http = require('http')
  , server = http.createServer(app)
  , io = require('socket.io').listen(server);
server.listen(3000);`

But angular-express-seed somehow merges the app and server variable together. How would I go about extracting the server from the app-variable to be able to use socket.io with this?

Best regards
Brian

**Comment by btford** [comment]
See: https://github.com/btford/angular-socket-io-seed
